import "oaidl.idl";
import "ocidl.idl";
import "mwcomtypes.idl";

[
  object,
  uuid("F8DE4D12-02A5-4539-A0E7-BA3F5C758EE1"),
  dual,
  helpstring("IClass1 Interface"),
  pointer_default(unique)
]
interface IClass1 : IDispatch
{
  [propget, id(1), helpstring("property MWFlags")]
  HRESULT MWFlags([out, retval] IMWFlags** ppvFlags);
  [propput, id(1), helpstring("property MWFlags")]
  HRESULT MWFlags([in] IMWFlags* pvFlags);

  [id(2), helpstring("Method anova_custom")]
  HRESULT anova_custom([in] VARIANT x, [in] VARIANT y);

  [propget, id(3), helpstring("property help")]
  HRESULT help([in] BSTR funcname, [out, retval] BSTR* helptext);

};
[
  uuid("4AB42CF6-0CFB-4E8E-B34C-9D414E2473FA"),
  version(1.0),
  helpstring("anova_custom 1.0 Type Library")
]
library anova_custom
{
  importlib("stdole32.tlb");
  importlib("stdole2.tlb");
  importlib("mwcomutil.tlb");

  [
    uuid("BACC926C-165D-4973-9C33-38629A8E52E2"),
    helpstring("Class1 Class")
  ]
  coclass Class1
  {
    [default] interface IClass1;
  };
};
